In [ ]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score,f1_score
from sklearn.metrics import classification_report
from sklearn import metrics

loading the preprocessed data set

In [ ]:
dataframe=pd.read_csv('normalized_data.csv')
dataframe

Unnamed: 0  fixed acidity  volatile acidity  ...  sulphates   alcohol  quality
0              0       0.247788          0.397260  ...   0.137725  0.153846        0
1              1       0.283186          0.520548  ...   0.209581  0.215385        0
2              2       0.283186          0.438356  ...   0.191617  0.215385        0
3              3       0.584071          0.109589  ...   0.149701  0.215385        1
4              4       0.247788          0.397260  ...   0.137725  0.153846        0
...          ...            ...               ...  ...        ...       ...      ...
1594        1594       0.141593          0.328767  ...   0.149701  0.323077        0
1595        1595       0.115044          0.294521  ...   0.257485  0.430769        1
1596        1596       0.150442          0.267123  ...   0.251497  0.400000        1
1597        1597       0.115044          0.359589  ...   0.227545  0.276923        0
1598        1598       0.123894          0.130137  ...   0.197605  0.400000        1

[1599 rows x 11 columns]

Here we are copying the dataset int a dataframe called data


In [ ]:
data = dataframe.copy()
data = data.drop('Unnamed: 0',axis = 1)
x = data.drop('quality',axis=1)
y = data['quality']
data

fixed acidity  volatile acidity  ...   alcohol  quality
0          0.247788          0.397260  ...  0.153846        0
1          0.283186          0.520548  ...  0.215385        0
2          0.283186          0.438356  ...  0.215385        0
3          0.584071          0.109589  ...  0.215385        1
4          0.247788          0.397260  ...  0.153846        0
...             ...               ...  ...       ...      ...
1594       0.141593          0.328767  ...  0.323077        0
1595       0.115044          0.294521  ...  0.430769        1
1596       0.150442          0.267123  ...  0.400000        1
1597       0.115044          0.359589  ...  0.276923        0
1598       0.123894          0.130137  ...  0.400000        1

[1599 rows x 10 columns]

Here we are spliting the data inorder to apply the Decision Tree classifer


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.5)
clf = DecisionTreeClassifier(max_depth=6)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
Training_score = clf.score(X_train,y_train)
Testing_score = clf.score(X_test,y_test)
print('training score is {} testing score is {}'.format(Training_score,Testing_score))


training score is 0.8560700876095119 testing score is 0.71125


In [ ]:
pred = clf.predict(X_test)
print("Confusion Matrix:" "\n",metrics.confusion_matrix(y_test, clf.predict(X_test)))
print()
print("Classification_Report:" "\n", metrics.classification_report(y_test, clf.predict(X_test))) 
print()
Accuracy = accuracy_score(y_test,pred)
print( Accuracy)

Confusion Matrix:
 [[313  80]
 [159 248]]

Classification_Report:
               precision    recall  f1-score   support

           0       0.66      0.80      0.72       393
           1       0.76      0.61      0.67       407

    accuracy                           0.70       800
   macro avg       0.71      0.70      0.70       800
weighted avg       0.71      0.70      0.70       800


0.70125


Here we are applying the Gaussian Navie Bayes model and Displayed the classifiaction Report

In [ ]:
clf2 = GaussianNB()
clf2.fit(X_train,y_train)
pred2 = clf2.predict(X_test)
Accuracy2 = accuracy_score(y_test,pred2)
print("the accuracy of the model is:", Accuracy2)
print("Confusion Matrix:" "\n",metrics.confusion_matrix(y_test, clf2.predict(X_test)))
print()
print("Classification_Report:" "\n", metrics.classification_report(y_test, clf2.predict(X_test))) 
print()
Training_score = clf2.score(X_train,y_train)
Testing_score = clf2.score(X_test,y_test)
print('training score is {} testing score is {}'.format(Training_score,Testing_score))

the accuracy of the model is: 0.7275
Confusion Matrix:
 [[250 127]
 [ 91 332]]

Classification_Report:
               precision    recall  f1-score   support

           0       0.73      0.66      0.70       377
           1       0.72      0.78      0.75       423

    accuracy                           0.73       800
   macro avg       0.73      0.72      0.72       800
weighted avg       0.73      0.73      0.73       800


training score is 0.7434292866082604 testing score is 0.7275


Here are Applying the linear regression and displaying the acuurary of the model as we cannot calculate the confusion matrix for this model as we have both numerical and categorical values.


In [ ]:
clf3 = LinearRegression()
clf3.fit(X_train,y_train)
pred3 = clf3.predict(X_test)
Training_score = clf3.score(X_train,y_train)
Testing_score = clf3.score(X_test,y_test)
print('training score is {} testing score is {}'.format(Training_score,Testing_score))



training score is 0.2731062816803955 testing score is 0.2993751320406458


Here we perform the logistic regression and then compute precision, recall for evaluating the accuracy.

In [ ]:
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)
score = logisticRegr.score(X_test, y_test)
print(score)
print("Confusion Matrix:" "\n",metrics.confusion_matrix(y_test, logisticRegr.predict(X_test)))
print()
print("Classification_Report:" "\n", metrics.classification_report(y_test, logisticRegr.predict(X_test))) 
print()
Training_score = clf.score(X_train,y_train)
Testing_score = clf.score(X_test,y_test)
print('training score is {} testing score is {}'.format(Training_score,Testing_score))

0.7525
Confusion Matrix:
 [[280  97]
 [101 322]]

Classification_Report:
               precision    recall  f1-score   support

           0       0.73      0.74      0.74       377
           1       0.77      0.76      0.76       423

    accuracy                           0.75       800
   macro avg       0.75      0.75      0.75       800
weighted avg       0.75      0.75      0.75       800


training score is 0.8560700876095119 testing score is 0.71125


Here we use different "k" values and try to analyze the proposed model and then we perform comaprisons and then at last based on the training and testing score we find the best "K" value, which oin our case would be k=7

In [ ]:
knnscores = pd.DataFrame(columns= ['K','Training score','Testing score'])
Training_score = []
Testing_score = []
k =[]
for i in range(1,25) :
    knnclf = KNeighborsClassifier(n_neighbors=i, p=1, metric='minkowski')
    knnclf.fit(X_train,y_train)
    Training_score.append(knnclf.score(X_train,y_train))
    Testing_score.append(knnclf.score(X_test,y_test))
    k.append(i)
knnscores['K'] = k
knnscores['Training score'] = Training_score
knnscores['Testing score'] = Testing_score
#print(knnscores)
print("Confusion Matrix:" "\n",metrics.confusion_matrix(y_test, knnclf.predict(X_test)))
print()
print("Classification_Report:" "\n", metrics.classification_report(y_test, knnclf.predict(X_test))) 
print()
knnscores


Confusion Matrix:
 [[284 109]
 [ 85 322]]

Classification_Report:
               precision    recall  f1-score   support

           0       0.77      0.72      0.75       393
           1       0.75      0.79      0.77       407

    accuracy                           0.76       800
   macro avg       0.76      0.76      0.76       800
weighted avg       0.76      0.76      0.76       800




K  Training score  Testing score
0    1        1.000000        0.71875
1    2        0.856070        0.69375
2    3        0.842303        0.72750
3    4        0.812265        0.74625
4    5        0.804756        0.75750
5    6        0.782228        0.76875
6    7        0.774718        0.74875
7    8        0.778473        0.75000
8    9        0.743429        0.73875
9   10        0.750939        0.75125
10  11        0.735920        0.75250
11  12        0.745932        0.75125
12  13        0.734668        0.74750
13  14        0.749687        0.75375
14  15        0.732165        0.75125
15  16        0.740926        0.75125
16  17        0.739675        0.73875
17  18        0.743429        0.75375
18  19        0.729662        0.73875
19  20        0.737171        0.75375
20  21        0.728411        0.75000
21  22        0.728411        0.75875
22  23        0.733417        0.75250
23  24        0.739675        0.75750